const express = require('express');
const router = express.Router();
const db = require('../db/client');
const crypto = require('crypto');
const Razorpay = require('razorpay');

const RAZORPAY_KEY_ID = process.env.VITE_RAZORPAY_KEY_ID || '';
const RAZORPAY_KEY_SECRET = process.env.RAZORPAY_KEY_SECRET || '';
const WEBHOOK_SECRET = process.env.RAZORPAY_WEBHOOK_SECRET || '';

let rzp = null;
if (RAZORPAY_KEY_ID && RAZORPAY_KEY_SECRET) {
  try {
    rzp = new Razorpay({
      key_id: RAZORPAY_KEY_ID,
      key_secret: RAZORPAY_KEY_SECRET
    });
  } catch (err) {
    console.error('[Payments] ❌ Failed to initialize Razorpay:', err.message);
  }
} else {
  console.warn('[Payments] ⚠️ Razorpay credentials (VITE_RAZORPAY_KEY_ID, RAZORPAY_KEY_SECRET) are missing. Payment order creation is disabled.');
}

// ─── 1. Sprint Config Tables (INR pricing in paise) ─────────────
const PLANS = {
  free_trial: { price: 0, credits: 100, storage_chars: 50000, max_sources: 3, max_file_mb: 5 },
  base: { price: 29900, credits: 2000, storage_chars: 100000, max_sources: 10, max_file_mb: 10 },
  pro: { price: 49900, credits: 5000, storage_chars: 300000, max_sources: 20, max_file_mb: 15 },
  growth: { price: 69900, credits: 15000, storage_chars: 500000, max_sources: 20, max_file_mb: 35 },
  // Annual Plans (Prices are per year in paise, credits are total for the year)
  base_annual: { price: 298800, credits: 24000, storage_chars: 100000, max_sources: 10, max_file_mb: 10 },
  pro_annual: { price: 478800, credits: 60000, storage_chars: 300000, max_sources: 20, max_file_mb: 15 },
  growth_annual: { price: 658800, credits: 180000, storage_chars: 500000, max_sources: 20, max_file_mb: 35 }
};

// ─── 2. Create Order Endpoint ───────────────────────────────────
router.post('/create-order', async (req, res) => {
  try {
    if (!rzp) {
      return res.status(501).json({ error: 'Payments are not enabled/configured on this self-hosted instance.' });
    }

    const { type, plan_id, pack_id, email, name, company } = req.body;
    let amount = 0;
    let itemId = '';

    if (type === 'plan') {
      if (!PLANS[plan_id] || plan_id === 'free_trial') {
        return res.status(400).json({ error: 'Invalid plan selected' });
      }
      amount = PLANS[plan_id].price;
      itemId = plan_id;
    } else {
      return res.status(400).json({ error: 'Invalid purchase type or recharge is no longer available' });
    }

    const options = {
      amount: amount,
      currency: 'INR',
      receipt: `kira_rcpt_${Date.now()}`,
      notes: {
        type: type,
        item_id: itemId,
        email: email?.toLowerCase().trim() || 'guest',
        name: name || '',
        company: company || ''
      }
    };

    const order = await rzp.orders.create(options);

    res.json({
      order_id: order.id,
      amount: order.amount,
      currency: order.currency,
      key: RAZORPAY_KEY_ID
    });
  } catch (err) {
    console.error('[Payments] ❌ Error creating order:', err);
    res.status(500).json({ error: 'Failed to create payment order' });
  }
});

// ─── 3. Webhook Handler ─────────────────────────────────────────
router.post('/webhook', async (req, res) => {
  try {
    const signature = req.headers['x-razorpay-signature'];

    // Uses the rawBody string generated by your existing index.js safely
    const rawBodyForSignature = req.rawBody || JSON.stringify(req.body);

    if (WEBHOOK_SECRET && signature) {
      const expectedSignature = crypto
        .createHmac('sha256', WEBHOOK_SECRET)
        .update(rawBodyForSignature)
        .digest('hex');

      if (expectedSignature !== signature) {
        console.warn('[Webhook] ❌ Signature mismatch');
        return res.status(401).json({ error: 'Invalid signature' });
      }
    }

    const payload = typeof req.body === 'string' ? JSON.parse(req.body) : req.body;
    const event = payload.event;

    if (event === 'payment.captured') {
      const payment = payload.payload.payment.entity;
      const { type, item_id, email, name, company } = payment.notes;
      const amountPaise = payment.amount || 0;

      console.log(`[Webhook] 💰 Captured | Type: ${type} | Item: ${item_id} | Email: ${email}`);

      try {
        // Update Customer Plan
        if (type === 'plan') {
          await db.query(`
            UPDATE customers 
            SET plan = $1, credit_balance = $2, trial_ends_at = NULL, subscription_status = 'paid'
            WHERE email = $3
          `, [item_id, PLANS[item_id].credits, email]);
        }

        // Fetch customer ID to log the receipt for your admin dashboard
        const custRes = await db.query(`SELECT id FROM customers WHERE email = $1`, [email]);
        if (custRes.rows.length > 0) {
          await db.query(`
            INSERT INTO payment_history (customer_id, razorpay_payment_id, razorpay_order_id, amount_paise, currency, plan_name, payment_status, email, name, company)
            VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
            ON CONFLICT DO NOTHING
          `, [custRes.rows[0].id, payment.id, payment.order_id || null, amountPaise, 'INR', item_id, 'captured', email, name, company]);
        }
      } catch (dbErr) {
        console.error('[Webhook] ❌ Database update failed:', dbErr.message);
      }
    }

    res.status(200).json({ received: true });
  } catch (err) {
    console.error('[Webhook] ❌ Processing error:', err.stack || err);
    res.status(500).json({ error: 'Webhook processing failed' });
  }
});

module.exports = router;